## © 2022 Nephio Authors
## Licensed under the Apache License 2.0
## SPDX-License-Identifier: Apache-2.0

---
- name: Create tmp clab directory
  ansible.builtin.file:
    path: "{{ tmp_directory }}/clab"
    state: directory
    mode: '0755'

- name: Copy clab binary to tmp_directory
  become: true
  ansible.builtin.copy:
    src: "{{ installer_lib }}/{{ item }}"
    dest: "{{ tmp_directory }}/clab/{{ item }}"
    mode: "0755"
    owner: "root"
    group: "root"
    remote_src: true
  with_items:
    - clab.deb

- name: Installing clab
  become: true
  shell: "dpkg -i {{ tmp_directory }}/clab/{{ item }}"
  with_items:
    - clab.deb

- name: Remove clab temp dir
  become: true
    file:
      path: "{{ tmp_directory }}/clab"
      state: absent