## © 2022 Nephio Authors
## Licensed under the Apache License 2.0
## SPDX-License-Identifier: Apache-2.0

---
- name: Unarchive nephio packages archive
  ansible.builtin.unarchive:
    src: "{{ installer_lib }}/nephio-packages.tar"
    dest: "{{ tmp_directory }}/nephio-packages"
    remote_src: true

- name: Copy {{ item.package }} to tmp_directory
  ansible.builtin.copy:
    src: "{{ tmp_directory }}/nephio-packages/nephio-packages/{{ item.package }}"
    dest: "{{ tmp_directory }}/{{ nephio.install_dir}}"
    remote_src: true

- name: Initialize {{ item.package }}
  become: true
  shell: kpt fn render {{ item.package }}
  args: 
    chdir: "{{ tmp_directory }}/{{ nephio.install_dir}}"
