## © 2022 Nephio Authors
## Licensed under the Apache License 2.0
## SPDX-License-Identifier: Apache-2.0

---
- name: Copy kubectl binary to tmp_directory
  become: true
  ansible.builtin.copy:
    src: "{{ installer_lib }}/{{ item }}"
    dest: "{{ tmp_directory }}/{{ item }}"
    mode: "0755"
    owner: "root"
    group: "root"
    remote_src: true
  with_items:
    - kubectl

- name: Copy kubectl binary to destination directory
  become: true
  ansible.builtin.copy:
    src: "{{ tmp_directory }}/{{ item }}"
    dest: "{{ bin_directory }}/{{ item }}"
    mode: "0755"
    owner: "root"
    group: "root"
    remote_src: true
  with_items:
    - kubectl
