## © 2023 Nephio Authors
## Licensed under the Apache License 2.0
## SPDX-License-Identifier: Apache-2.0

---
- include_tasks: "podman-{{ ansible_os_family }}.yaml"
  when: ansible_distribution == 'Ubuntu'

- name: include podman pre-install tasks
  ansible.builtin.include_tasks: pre-req.yaml

- name: installing podman
  become: true
  ansible.builtin.package:
    name: "podman"
    state: latest

- name: create podman network for kind
  containers.podman.podman_network:
    name: kind
    driver: bridge

- name: add docker alias for podman
  lineinfile:
    path=/home/{{ cloud_user }}/.bashrc
    line="alias docker=podman"

- name: source the file
  shell: "source /home/{{ cloud_user }}/.bashrc"
  args:
    executable: /bin/bash

# https://stackoverflow.com/questions/72690495/interact-with-podman-docker-via-socket-in-redhat-9
- name: enable podman systemd units
  block:
    - name: Unmask and enable podman.socket
      ansible.builtin.systemd:
        name: podman.socket
        enabled: true
        state: started
        masked: no
    - name: Unmask, Enable and start podman.service
      ansible.builtin.systemd:
        name: podman.service
        enabled: true
        masked: no
        state: started
  become: true
