## © 2023 Nephio Authors
## Licensed under the Apache License 2.0
## SPDX-License-Identifier: Apache-2.0

---
- name: fail if ubuntu version is below 22.04 and podman install is requested
  ansible.builtin.fail:
    msg: Ubuntu version to be 22.04 or greater when podman install is requested
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version | int < 22

- name: setup apt repo for podman
  block:
    - name: kubic podman repo key add
      become: true
      ansible.builtin.get_url:
        url: "https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_{{ ansible_distribution_version }}/Release.key"
        dest: /etc/apt/trusted.gpg.d/kubic.key

    - name: kubic podman repo apt source
      become: true
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/trusted.gpg.d/kubic.key] https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_{{ ansible_distribution_version }}/ /"
        state: present
