## © 2023 Nephio Authors
## Licensed under the Apache License 2.0
## SPDX-License-Identifier: Apache-2.0

---
- name: create system directory related to podman
  become: true
  ansible.builtin.file:
    path: /etc/systemd/system/user@.service.d
    state: directory

- name: setting systemd property "Delegate=yes"
  become: true
  ansible.builtin.copy:
    content: |
      [Service]
      Delegate=yes
    dest: /etc/systemd/system/user@.service.d/delegate.conf

- name: system daemon reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
